services:
  node:
    image: node
    tty: true
    working_dir: "/var/app"
    volumes:
     - "./:/var/app"
     # - node_modules:/var/app/node_modules:cached
     - /var/app/.git
    ports:
      - "3000:3000"
volumes:
  node_modules:
    driver: local
